### ISSUE TITLE
Entering IP for scanning different subnet looses focus

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#13]
**Describe the bug**
After every keystroke in the field for entering a subnet to be scanned the focus is lost and you have to tap the field for next number

**To Reproduce**
1. Go to Deep Scan
2. Click on Menu, field Subnet
3. Try to edit field
4. After every keystroke the focus is lost, even backspace doesn't work

**Expected behavior*
Field subnet should be editable

**Smartphone (please complete the following information):**
 - Device: Allducube Freer X9 & Doogee Y8
 - OS: Android 6.1 & 9
 - Chrome and Webview updated to the last versions

**Additional context**
App version 1.2 tested

**Comment by Wiki591** [comment]
Just noticed: the cursor is set to the beginning of the field during typing

**Comment by iotschmied** [comment]
Fixed in version 1.2.2.
Please verify.

**Comment by Wiki591** [comment]
Works as expected
