### ISSUE TITLE
Character set translation adding device from deep scan missing

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#14]
**Describe the bug**
Adding a device with a name containing special characters the special characters are not translated

**To Reproduce**
1. create a device with name "Büro"
2. Go to Deep network scan
3. The device containing special characters shows up with "BÃ¼ro"
4. After Adding the device it is not possible to correct the name

**Expected behavior**
Characters should be translated - at least manual correction should be possible

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/38845308/78570060-bdff4380-7824-11ea-9b6c-141a979c4509.jpg)

**Additional context**
Adding the device manually works

**Comment by iotschmied** [comment]
Fixed in version 1.2.2.
Please verify.

**Comment by Wiki591** [comment]
Works as expected
![20200409_135815900](https://user-images.githubusercontent.com/38845308/78893171-1d4e9500-7a6b-11ea-809b-106e46068e71.jpeg)
