### ISSUE TITLE
Typo in German localization

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#15]
**Describe the bug**
key replaceDeviceExistSubTitle is translated with "Gewählte Geräte werden ind der App aktualisiert"

**Expected behavior**
should be translated with "Gewählte Geräte werden in der App aktualisiert"

**Comment by Wiki591** [comment]
After stepping through the app I modified the German localizations a little bit, typo is corrected
[Translations.zip](https://github.com/iotschmied/IotMage/files/4439211/Translations.zip)

**Comment by iotschmied** [comment]
Is the "replaceDeviceExistSubTitle" key the only incorrect translation?

**Comment by Wiki591** [comment]
No, for understandability I've changed I think five items

**Comment by iotschmied** [comment]
Fixed in version 1.2.1.
Please verify.

**Comment by Wiki591** [comment]
Looks pretty good
