### ISSUE TITLE
Adding MAC address automatically in manually added device

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#16]
**Is your feature request related to a problem? Please describe.**
No, not at all, would be convenient
Adding a device manually which is currently in deep sleep will be saved with zeroed MAC because the button "GET INFO" cannot work at this moment.
The MAC itself is not possible to be edited, same with the name of the device.

**Describe the solution you'd like**
It would be convenient if the app uses the first contact to the awakening device to fill in the missing information.

**Describe alternatives you've considered**
At least it would be helpful to be able to edit the MAC and name of the device manually

**Comment by iotschmied** [comment]
Implemented in version 1.2.3.
Please verify.

**Comment by Wiki591** [comment]
Eeehm, Google doesn't offer me an update?

**Comment by iotschmied** [comment]
The update is still being reviewed.

**Comment by Wiki591** [comment]
OK, will be patient

**Comment by Wiki591** [comment]
Still patient, but whats going on? Neither 1.2.3 nor 1.2.4 are offered?

**Comment by iotschmied** [comment]
![image](https://user-images.githubusercontent.com/61375218/79098797-66ecf780-7d6b-11ea-9f96-070004357dde.png)
:(

**Comment by Wiki591** [comment]
Works, nice
