### ISSUE TITLE
The rendering of the webpage of ESPEasy is not usable

### ISSUE THREAD

**Issue by iotschmied** [iotschmied/IotMage#17]
From the feedback:
> If a page is larger than can be displayed (e.g. controller settings page) then you cannot scroll to the bottom to access the submit button.
> Just as if the top of the page is forced to remain visible.
> 
> I'm using Motorola One Vision running Android 10.

**Comment by Wiki591** [comment]
Looks good, scrolling is working.

Response time of the different pages quite slow

**Comment by iotschmied** [comment]
The app uses Native WebView, I can't say at the moment why it might work slowly as I have just one phone and three Esp8266 devices.
I will investigate when possible.
I don't close the issue since the fix in version 1.2.1 is kind of workaround. Now AppBar has fixed visibility, but In the previous version the AppBar was working as it works in modern mobile browsers - it hid when user was scrolling up the page.
I will come back to this when implement more priority items.

**Comment by iotschmied** [comment]
Created #20.
