### ISSUE TITLE
Loading timer doesn't set seconds

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#21]
**Describe the bug**
Initiating the connection to a device configured for deep sleep starts a timer while waiting for the connection. Seconds are counted up, after 60seconds the mintute is counted up, but the seconds are displayed >60, i.e. instead of diplaying 00:01:23 00:01:83 is displayed

**To Reproduce**
1. Opn connection to a deep sleep device which will not wake up during the next 70 seconds or so
2. Have a look at the clock >1 minute

**Comment by iotschmied** [comment]
Fixed in version 1.2.2.
Please verify.

**Comment by Wiki591** [comment]
Works as expected
