### ISSUE TITLE
"Scan Network" does nothing

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#26]
**Describe the bug**
Hitting the menu point "Scan Network" does nothing
I don't know the functionality of this menu entry, for me it is obsolete

**Comment by iotschmied** [comment]
This is an mDNS scanner - in some cases it might work much faster than the Deep Scan functionality.
The firmware of a device must be complied with the `define FEATURE_MDNS` to be discoverable on this screen.

**Comment by Wiki591** [comment]
Should be named in the menu entry. Imho you have the deep scan functionality accelerated in such an incredible manner compared to the first time I tried this scan in the past (earliest version) that this point may be obsolete. I don't think that many devices are selfcompiled with the mDNS activated.

**Comment by Wiki591** [comment]
Additionally: For the ones which followed the thread in the forum that name "Deep Network Scan" is understandable. In the case the "Scan Network" would be eliminated, the "Deep Network Scan" could be renamed to "Scan Network"

**Comment by iotschmied** [comment]
One more advantage of using this page: mDNS scan can find devices from different subnets.
