### ISSUE TITLE
Rename "Scan Wifi"

### ISSUE THREAD

**Issue by Wiki591** [iotschmied/IotMage#27]
**Is your feature request related to a problem? Please describe.**
As an uninformed (first) user it is not clear, what this menu entry does

**Describe the solution you'd like**
To clarify the function it could be renamed to "Scan Wifi for ESPEasy APs (uncofigured devices)" 
(de: "Scan Wifi nach ESPEasy Aps (unkonfigurierte Geräte)")
This would it make more useful/explainable for inexperienced users, imho enough space for the extended description of the menu entry is available.

**Comment by iotschmied** [comment]
That's a too long description, but I am thinking of replacing part of titles with icons - and creating more help screens/flyout hints. In this case your suggestion sounds reasonable.
